services:
  starlight-dev:
    build: .
    container_name: starlight-dev
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.astro
      - /app/dist
    working_dir: /app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=4321
