services:
  starlight-dev:
    build: .
    container_name: starlight-dev
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules  # Anonymous volume
      - /app/.astro        # Anonymous volume
      - /app/dist          # Anonymous volume
    working_dir: /app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=4321

# No volumes section needed with anonymous volumes