services:
  starlight-dev:
    build: .
    container_name: starlight-dev
    ports:
      - "4321:4321"
    # No volumes - just use what's in the image
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - PORT=4321